import { mkdir, readFile, writeFile } from "fs/promises";
import { dirname, join } from "path";
import { getSpsNoteIndex } from "./note-index";
import { resolveSpsVaultDir } from "./sps-storage";
import type {
  SpsContextPackInput,
  SpsContextPackResult,
} from "../shared/sps-types";

export interface ContextPackNote {
  path: string;
  title: string;
  body: string;
}

export interface ContextPackSource {
  pageId: string;
  title: string;
  root: ContextPackNote;
  backlinks: ContextPackNote[];
  outgoing: ContextPackNote[];
  tasks: ContextPackNote[];
  unresolvedQuestions: string[];
}

export function buildContextPackMarkdown(
  source: ContextPackSource,
  options: { maxBytes?: number } = {},
): SpsContextPackResult {
  const included = uniquePaths([
    source.root,
    ...source.backlinks,
    ...source.outgoing,
    ...source.tasks,
  ]);
  const sections = [
    `# Context Pack: ${source.title}`,
    `## Provenance\n- Root note: ${source.root.path}\n- Generated by Hermes/SPS from local Markdown vault files.`,
    `## Included paths\n${included.map((p) => `- ${p}`).join("\n") || "- none"}`,
    renderNote("Selected note", source.root),
    renderNotes("Backlinks", source.backlinks),
    renderNotes("Linked sources", source.outgoing),
    renderNotes("Related tasks", source.tasks),
    `## Unresolved questions\n${source.unresolvedQuestions.map((q) => `- ${q}`).join("\n") || "- none found"}`,
  ];
  return clampMarkdown(sections.join("\n\n"), included, options.maxBytes);
}

export async function buildContextPack(
  input: SpsContextPackInput,
  profile?: string,
): Promise<SpsContextPackResult> {
  const vaultDir = resolveSpsVaultDir(profile);
  const pagePath = input.pageId.endsWith(".md")
    ? input.pageId
    : `${input.pageId}.md`;
  const root = await readNote(vaultDir, pagePath);
  if (!root) throw new Error(`Page not found: ${input.pageId}`);
  const index = await getSpsNoteIndex(profile);
  const backlinks =
    input.includeBacklinks === false
      ? []
      : await readMany(vaultDir, index.backlinks(pagePath));
  const outgoing =
    input.includeSources === false
      ? []
      : await readMany(
          vaultDir,
          index
            .links()
            .filter((edge) => edge.source === pagePath)
            .map((edge) => edge.target),
        );
  const tasks =
    input.includeTasks === false
      ? []
      : await readMany(
          vaultDir,
          index.query({ scope: "tasks", limit: 50 }).map((row) => row.path),
        );
  const result = buildContextPackMarkdown(
    {
      pageId: input.pageId,
      title: root.title,
      root,
      backlinks,
      outgoing,
      tasks,
      unresolvedQuestions: extractQuestions([root, ...backlinks, ...outgoing]),
    },
    { maxBytes: input.maxBytes },
  );
  if (input.save) {
    const path = `_context-packs/${safeSlug(input.pageId)}.md`;
    const target = join(vaultDir, path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, result.markdown, "utf-8");
    result.savedPath = path;
  }
  return result;
}

function renderNote(label: string, note: ContextPackNote): string {
  return `## ${label}: ${note.title}\nPath: ${note.path}\n\n${note.body.trim() || "_Empty note._"}`;
}

function renderNotes(label: string, notes: ContextPackNote[]): string {
  if (notes.length === 0) return `## ${label}\nNone.`;
  return [
    `## ${label}`,
    ...notes.map((note) => renderNote(note.title, note)),
  ].join("\n\n");
}

function uniquePaths(notes: ContextPackNote[]): string[] {
  return [...new Set(notes.map((note) => note.path))].sort();
}

function clampMarkdown(
  markdown: string,
  includedPaths: string[],
  maxBytes = 64_000,
): SpsContextPackResult {
  const bytes = Buffer.byteLength(markdown, "utf-8");
  if (bytes <= maxBytes) return { markdown, includedPaths, truncated: false };
  const suffix = "\n\n[truncated]\n";
  const budget = Math.max(0, maxBytes - Buffer.byteLength(suffix, "utf-8"));
  let clipped = markdown;
  while (Buffer.byteLength(clipped, "utf-8") > budget)
    clipped = clipped.slice(0, -1);
  return { markdown: `${clipped}${suffix}`, includedPaths, truncated: true };
}

async function readMany(
  vaultDir: string,
  paths: string[],
): Promise<ContextPackNote[]> {
  const notes = await Promise.all(
    paths.map((path) => readNote(vaultDir, path)),
  );
  return notes.filter((note): note is ContextPackNote => note !== null);
}

async function readNote(
  vaultDir: string,
  path: string,
): Promise<ContextPackNote | null> {
  try {
    const raw = await readFile(join(vaultDir, path), "utf-8");
    const title =
      /^---[\s\S]*?title:\s*"?([^"\n]+)"?[\s\S]*?---/.exec(raw)?.[1] ||
      /^#\s+(.+)$/m.exec(raw)?.[1] ||
      path.replace(/\.md$/, "");
    const body = raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, "");
    return { path, title: title.trim(), body };
  } catch {
    return null;
  }
}

function extractQuestions(notes: ContextPackNote[]): string[] {
  const questions = new Set<string>();
  for (const note of notes) {
    for (const line of note.body.split("\n")) {
      const clean = line.trim().replace(/^[-*]\s+/, "");
      if (clean.endsWith("?")) questions.add(clean);
    }
  }
  return [...questions].sort().slice(0, 20);
}

function safeSlug(raw: string): string {
  return raw.replace(/\.md$/, "").replace(/[^A-Za-z0-9_-]+/g, "-") || "context";
}
